# This is a TOML document. Boom
[env]
    host = "job0"

[discovery]
    nodes = ["127.0.0.1:7171","127.0.0.1:7170"]
    host = "job0"

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]
