# This is a TOML document. Boom
[env]
    host = "job0"
    zone = "gz"
    region = "gz0001"
    deployEnv = "dev"

[discovery]
    nodes = ["127.0.0.1:7171"]
    host = "job0"
    zone = "gz"
    region = "gz0001"
    env = "dev"

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]
